version: '3.9'

services:
  dev-db:
    image: postgres:16
    volumes:
      # - ./app/db/postgresql/data:/var/lib/postgresql/data
      - ./app/db/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:${DATABASE_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
  
  test-db:
    image: postgres:16
    volumes:
      # - ./app/db/postgresql/data:/var/lib/postgresql/data
      - ./app/db/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5433:${TEST_DATABASE_PORT}"
    environment:
      - POSTGRES_PASSWORD=${TEST_DATABASE_PASSWORD}
      - POSTGRES_USER=${TEST_DATABASE_USERNAME}
      - POSTGRES_DB=${TEST_DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
