# syntax=docker/dockerfile:1

# Rubyのバージョンを指定
ARG RUBY_VERSION=3.2.3
FROM ruby:$RUBY_VERSION as base

# アプリケーションの作業ディレクトリを設定
WORKDIR /rails

# 開発環境変数を設定
ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="production"

# 必要なパッケージをインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev pkg-config git libvips

# GemfileとGemfile.lockをコピーしてbundle installを実行
COPY Gemfile Gemfile.lock ./
RUN bundle install

# ホストのカレントディレクトリからコンテナの作業ディレクトリにアプリケーションのコードをコピー
# 開発環境では、このステップはdocker-compose.ymlのvolumesで上書きされることが多い
COPY . .

# binファイルを実行可能にする
RUN chmod +x bin/*

