# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: zemi_backend_test
          POSTGRES_USER: zemi_backend
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    env:
      RAILS_ENV: test
      TEST_DATABASE_NAME: zemi_backend_test
      TEST_DATABASE_USERNAME: zemi_backend
      TEST_DATABASE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      TEST_DATABASE_HOST: localhost
      TEST_DATABASE_PORT: 5432
      BUNDLE_WITHOUT: "development production"
      BUNDLE_WITH: "test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bundle exec rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rails test

  lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: "development production test"
      BUNDLE_WITH: "linters"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel
